<?php

namespace App\Filament\Resources\Clients\RelationManagers;

use App\Filament\Support\DownloadPdfAction;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

/**
 * Read-only list of every generated (persisted, numbered) Statement of
 * Account for this client — a Codex review finding on PR #4: the
 * "Generate Statement of Account" action only surfaced a raw URL inside a
 * self-dismissing notification, with no resource, relation manager, or
 * other listing anywhere from which a previously generated statement
 * could be reopened. Every row is written only by
 * App\Actions\Reports\GenerateStatementOfAccount (via
 * App\Filament\Resources\Clients\Tables\ClientsTable's row action), never
 * a generic create/edit here — a preview is never persisted at all (see
 * App\Models\StatementOfAccount's own docblock).
 */
class StatementOfAccountsRelationManager extends RelationManager
{
    /**
     * Phase 06B Slice 5 (docs/rebuild/specs/06b-ux-browser-soa/Specs.md) —
     * see the identical note on every other relation manager in this app:
     * Filament's lazy relation-manager loading never actually initializes
     * on a genuine full page load.
     */
    protected static bool $isLazy = false;

    protected static string $relationship = 'statementOfAccounts';

    protected static ?string $title = 'Statements of Account';

    public function form(Schema $schema): Schema
    {
        return $schema->components([]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('number')
            ->defaultSort('generated_at', 'desc')
            ->columns([
                TextColumn::make('number'),
                TextColumn::make('period_start')->date(),
                TextColumn::make('period_end')->date(),
                TextColumn::make('opening_balance')->numeric(),
                TextColumn::make('closing_balance')->numeric(),
                TextColumn::make('generatedBy.name')->label('Generated by'),
                TextColumn::make('generated_at')->dateTime(),
            ])
            ->recordActions([
                DownloadPdfAction::statementOfAccount(),
            ]);
    }

    public function isReadOnly(): bool
    {
        return true;
    }
}
