<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * See docs/invoiceninja-v4-schema-reference.md §2.7 and
     * docs/filament-admin-layout-design.md §2.7 — a full HTML/CSS
     * document (quote cover letters/SOWs), separate from Invoices/Quotes
     * rather than bolted onto them. `invoice_id` links to the invoice
     * generated by App\Services\ProposalConverter once accepted, so
     * "already converted" can be checked directly rather than needing a
     * reverse column on `invoices`.
     */
    public function up(): void
    {
        Schema::create('proposals', function (Blueprint $table) {
            $table->id();
            $table->foreignId('company_id')->constrained()->cascadeOnDelete();
            $table->foreignId('client_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('proposal_template_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('invoice_id')->nullable()->constrained()->nullOnDelete();
            $table->unsignedInteger('legacy_proposal_id')->nullable();

            $table->string('title');
            $table->longText('html')->nullable();
            $table->longText('css')->nullable();
            $table->string('status')->default('draft'); // App\Enums\ProposalStatus
            $table->decimal('amount', 15, 2)->default(0);
            $table->date('valid_until')->nullable();

            $table->timestamp('sent_at')->nullable();
            $table->timestamp('viewed_at')->nullable();
            $table->timestamp('responded_at')->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('proposals');
    }
};
