<?php

namespace App\Livewire;

use App\Actions\Reports\GenerateStatementOfAccount;
use App\Models\Client;
use App\Models\Company;
use App\Models\StatementOfAccount;
use App\Services\BillingMailer;
use App\Services\Reports\BuildStatementOfAccount;
use App\Support\Tenancy\Tenancy;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Carbon;
use Livewire\Attributes\Layout;
use Livewire\Component;
use RuntimeException;
use TallStackUi\Traits\Interactions;

/**
 * The TALL-stack Statement of Account document view — Phase "Statement of
 * Accounts" of docs/rebuild/outputs/ui-rebuild/25-tallstack-full-rebuild-plan.md,
 * built against Stitch screen "Statement of Account — Preview &
 * Issuance Ledger (Axen Technology Variant)" and its own prompt 17
 * (docs/rebuild/outputs/ui-rebuild/26-stitch-missing-screens-prompts.md).
 *
 * Two modes, driven by whether a real `StatementOfAccount` row was bound:
 * - **Preview** (`statementOfAccount` null) — calls
 *   App\Services\Reports\BuildStatementOfAccount::build() directly on
 *   every render, exactly like App\Http\Controllers\
 *   StatementOfAccountPreviewController already does for the PDF route
 *   this page now supersedes as the primary "Preview" destination from
 *   App\Livewire\TallStackClientDetail. Never persisted, freely
 *   regenerated by changing the period.
 * - **Issued** (`statementOfAccount` bound) — renders the frozen
 *   `snapshot` recorded by App\Actions\Reports\GenerateStatementOfAccount
 *   at generation time. Never recomputed live, never editable, never
 *   regenerable from this page.
 *
 * The printed-document ledger composition below (merging invoices/
 * credits/payments into one chronological table with a running balance)
 * mirrors resources/views/pdf/statement-of-account.blade.php's own inline
 * PHP block exactly — display-only formatting over BuildStatementOfAccount's
 * already-computed `balance_contribution` fields, not a second calculation.
 * "Download PDF" reuses that existing PDF view/route entirely unchanged.
 */
#[Layout('components.tallstack.app')]
class TallStackStatementOfAccount extends Component
{
    use Interactions;

    public Company $company;

    public Client $client;

    public ?StatementOfAccount $statementOfAccount = null;

    public bool $isPreview = true;

    public string $periodStart;

    public string $periodEnd;

    public function mount(Company $company, Client $client, ?StatementOfAccount $statementOfAccount = null): void
    {
        abort_unless(auth()->user()->canAccessTenant($company), 403);

        $this->company = $company;

        app(Tenancy::class)->set($company);

        // Route binding happens before app(Tenancy::class)->set() above
        // activates BelongsToCompany's scope — same explicit re-check
        // every other TALL-stack page uses for its own bound records.
        abort_unless($client->company_id === $company->id, 404);
        $this->client = $client;

        if ($statementOfAccount) {
            abort_unless(
                $statementOfAccount->company_id === $company->id
                    && $statementOfAccount->client_id === $client->id,
                404
            );

            $this->statementOfAccount = $statementOfAccount->loadMissing('client', 'company');
            $this->isPreview = false;
            $this->periodStart = $statementOfAccount->period_start->toDateString();
            $this->periodEnd = $statementOfAccount->period_end->toDateString();

            return;
        }

        $this->isPreview = true;
        $this->periodStart = request()->query('period_start') ?: now()->startOfMonth()->toDateString();
        $this->periodEnd = request()->query('period_end') ?: now()->endOfMonth()->toDateString();
    }

    /**
     * Preview-only: the "this becomes a permanent numbered record —
     * cannot be un-generated" action from prompt 17. Reuses
     * App\Actions\Reports\GenerateStatementOfAccount unmodified — this
     * page is the only caller besides TallStackClientDetail's own modal,
     * and both call the exact same action.
     */
    public function generateAndIssue(): void
    {
        $this->authorize('update', $this->client);

        $data = $this->validate([
            'periodStart' => ['required', 'date'],
            'periodEnd' => ['required', 'date', 'after_or_equal:periodStart'],
        ]);

        $statementOfAccount = app(GenerateStatementOfAccount::class)->generate(
            $this->client,
            Carbon::parse($data['periodStart']),
            Carbon::parse($data['periodEnd']),
            auth()->user(),
        );

        $this->toast()->success('Statement of Account generated', "Number: {$statementOfAccount->number}")->send();

        $this->redirect(route('tallstack.clients.statement-of-account', [
            'company' => $this->company,
            'client' => $this->client,
            'statementOfAccount' => $statementOfAccount,
        ]), navigate: false);
    }

    /**
     * Issued-only: emails the frozen PDF to the client's resolved billing
     * contact, following App\Services\BillingMailer::sendPortalLink()'s
     * exact "no dedicated CompanySetting template column" pattern — see
     * that method's own docblock for why a hardcoded subject/body is
     * correct here rather than inventing a new settings field.
     */
    public function emailToClient(): void
    {
        abort_if($this->isPreview, 404);

        $this->authorize('update', $this->client);

        try {
            app(BillingMailer::class)->sendStatementOfAccount($this->statementOfAccount);
            $this->toast()->success('Statement of Account emailed to client.')->send();
        } catch (RuntimeException $e) {
            $this->toast()->error('Could not email Statement of Account', $e->getMessage())->send();
        }
    }

    public function render(BuildStatementOfAccount $builder): View
    {
        if ($this->isPreview) {
            $snapshot = $builder->build($this->client, $this->periodStart, $this->periodEnd);

            $soa = new StatementOfAccount([
                'company_id' => $this->company->id,
                'client_id' => $this->client->id,
                'period_start' => $this->periodStart,
                'period_end' => $this->periodEnd,
                'opening_balance' => $snapshot['opening_balance'],
                'closing_balance' => $snapshot['closing_balance'],
                'snapshot' => $snapshot,
            ]);
            $soa->setRelation('company', $this->company);
            $soa->setRelation('client', $this->client);
        } else {
            $soa = $this->statementOfAccount;
        }

        return view('livewire.tallstack-statement-of-account', [
            'soa' => $soa,
        ])->layoutData([
            'company' => $this->company,
            'active' => 'clients',
            'title' => 'Statement of Account — '.$this->client->name,
        ]);
    }
}
