<?php

namespace App\Models;

use App\Enums\InvoiceStatus;
use App\Enums\InvoiceType;
use App\Enums\PricingMode;
use App\Models\Concerns\BelongsToCompany;
use App\Models\Concerns\Holdable;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\SoftDeletes;

#[Fillable([
    'company_id', 'client_id', 'legacy_invoice_id',
    'type', 'status', 'number', 'po_number', 'invoice_date', 'due_date',
    'currency_code', 'exchange_rate', 'discount', 'discount_is_percentage',
    'terms', 'public_notes', 'private_notes', 'footer',
    'is_recurring', 'recurring_frequency', 'recurring_start_date', 'recurring_end_date',
    'recurring_template_id', 'auto_bill', 'converted_from_quote_id',
    'sales_order_id', 'pricing_mode', 'original_invoice_id', 'void_reason', 'correction_reason',
    'document_language',
])]
class Invoice extends Model
{
    use BelongsToCompany, Holdable, SoftDeletes;

    protected function casts(): array
    {
        return [
            'type' => InvoiceType::class,
            'status' => InvoiceStatus::class,
            'pricing_mode' => PricingMode::class,
            'invoice_date' => 'date',
            'due_date' => 'date',
            'partial_due_date' => 'date',
            'recurring_start_date' => 'date',
            'recurring_end_date' => 'date',
            'recurring_last_sent_at' => 'datetime',
            'sent_at' => 'datetime',
            'viewed_at' => 'datetime',
            'approved_at' => 'datetime',
            'issued_at' => 'datetime',
            'voided_at' => 'datetime',
            'held_at' => 'datetime',
            'is_recurring' => 'boolean',
            'auto_bill' => 'boolean',
            'discount_is_percentage' => 'boolean',
            'exchange_rate' => 'decimal:4',
            'discount' => 'decimal:2',
            'subtotal' => 'decimal:2',
            'tax_total' => 'decimal:2',
            'total' => 'decimal:2',
            'amount_paid' => 'decimal:2',
            'balance' => 'decimal:2',
            'partial_amount' => 'decimal:2',
        ];
    }

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function client(): BelongsTo
    {
        return $this->belongsTo(Client::class);
    }

    public function items(): HasMany
    {
        return $this->hasMany(InvoiceItem::class)->orderBy('sort_order');
    }

    public function invitations(): HasMany
    {
        return $this->hasMany(Invitation::class);
    }

    public function documents(): MorphMany
    {
        return $this->morphMany(Document::class, 'documentable');
    }

    public function payments(): HasMany
    {
        return $this->hasMany(Payment::class);
    }

    public function credits(): HasMany
    {
        return $this->hasMany(Credit::class);
    }

    /** The recurring template that generated this invoice, if any. */
    public function recurringTemplate(): BelongsTo
    {
        return $this->belongsTo(self::class, 'recurring_template_id');
    }

    /** Invoices generated from this recurring template. */
    public function generatedInvoices(): HasMany
    {
        return $this->hasMany(self::class, 'recurring_template_id');
    }

    /** The quote this invoice was converted from, if any. */
    public function convertedFromQuote(): BelongsTo
    {
        return $this->belongsTo(self::class, 'converted_from_quote_id');
    }

    /** For a quote: the invoice(s) generated by converting it, if any. */
    public function convertedInvoices(): HasMany
    {
        return $this->hasMany(self::class, 'converted_from_quote_id');
    }

    /** The Phase 03 Job this invoice bills against, when it has one. */
    public function salesOrder(): BelongsTo
    {
        return $this->belongsTo(SalesOrder::class);
    }

    /** The invoice this one amends or reissues, if any — never edited itself. */
    public function originalInvoice(): BelongsTo
    {
        return $this->belongsTo(self::class, 'original_invoice_id');
    }

    /** The amendment/reissue created against this invoice, if any. */
    public function correction(): HasOne
    {
        return $this->hasOne(self::class, 'original_invoice_id');
    }

    public function taxSnapshot(): HasOne
    {
        return $this->hasOne(InvoiceTaxSnapshot::class);
    }

    public function taxRecap(): HasOne
    {
        return $this->hasOne(TaxRecap::class);
    }

    public function allocations(): HasMany
    {
        return $this->hasMany(PaymentAllocation::class);
    }

    /**
     * Printed-document language: this invoice's own override when set,
     * otherwise the owning company's `default_document_language`, otherwise
     * Bahasa Indonesia — see
     * docs/rebuild/specs/06-documents-portal-reporting/Specs.md "Printed
     * documents default to Bahasa Indonesia with per-document English
     * override."
     */
    public function resolveDocumentLanguage(): string
    {
        return $this->document_language ?? $this->company->settings?->default_document_language ?? 'id';
    }
}
